//
// Created by urdmi on 17.12.2023.
//

#ifndef DIPLOM_ESP32_MQTT_ADAPTER_TEST_H
#define DIPLOM_ESP32_MQTT_ADAPTER_TEST_H

#define ESP_MQTT_ADAPTER
#define MAX_DELAY_SEND_DATA 10000000
#define BASE_TOPIC_NAME "gb_iot/2950_UDA/%s"

#endif //DIPLOM_ESP32_MQTT_ADAPTER_TEST_H
